version: "3"

services:

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    networks:
      - bus-network
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    restart: unless-stopped

  shortener:
    build: .
    depends_on:
      - postgres
#    env_file:
#      - .env
    environment:
      - DB_CONNECTION=5432
    ports:
      - "10000:10000"
      - "10010:10010"
    networks:
      - bus-network
    restart: unless-stopped

networks:
  bus-network:
    driver: bridge